# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170724_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='access_token',
        ),
    ]
