# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 00:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170724_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(default=datetime.date(2017, 8, 3)),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='max_age',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='user',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='user',
            name='show_gender',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
