# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170803_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 1, 1, 31, 71175)),
        ),
    ]
