# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170803_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
