# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170803_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='user_description',
        ),
    ]
