# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170803_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
