# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='user_a',
            new_name='user_one',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='user_b',
            new_name='user_two',
        ),
    ]
